# Generated by Django 4.0.4 on 2022-05-09 08:20

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['added']},
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='https://youtu.be/dQw4w9WgXcQ'),
        ),
    ]
