# Generated by Django 4.0.4 on 2022-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='session_key_2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
