# Generated by Django 4.0.4 on 2022-06-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='temp', max_length=150)),
                ('session_key', models.CharField(default='temp', max_length=150)),
                ('first_name', models.CharField(default='temp', max_length=150)),
                ('last_name', models.CharField(default='temp', max_length=150)),
                ('email', models.EmailField(default='temp@temp.com', max_length=150)),
                ('password1', models.CharField(default='temp', max_length=150)),
                ('password2', models.CharField(default='temp', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='pythonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codearea', models.TextField()),
                ('output', models.TextField()),
                ('session_key', models.TextField(null=True)),
                ('username', models.TextField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
