# Generated by Django 4.0.4 on 2022-05-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncode',
            name='session_key',
            field=models.TextField(default=None),
        ),
    ]
