# Generated by Django 4.0.4 on 2022-05-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_pythoncode_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncode',
            name='session_key',
        ),
    ]
