# Generated by Django 4.0.4 on 2022-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_order_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
