# Generated by Django 4.0.4 on 2022-05-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_pythoncode_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncode',
            name='session_key',
            field=models.TextField(null=True),
        ),
    ]
