# Generated by Django 4.0.4 on 2022-07-13 13:57

from django.db import migrations
from django.contrib.auth.models import User
def initialize(apps, schema_editor):
    for i in range(1,10):
        t = User.objects.create_user(username="TM20220000"+str(i), password="TM20220000"+str(i))
        t.save()
    for i in range(10,100):
        t = User.objects.create_user(username="TM2022000"+str(i), password="TM2022000"+str(i))
        t.save()
class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20220713_1119'),
    ]

    operations = [
        migrations.RunPython(initialize)
    ]
