# Generated by Django 4.0.4 on 2022-08-15 04:50

from django.db import migrations, transaction
from django.contrib.auth.models import User
def initialize(apps, schema_editor):
    for i in range(100,1000):
        try:
            with transaction.atomic():
            	t = User.objects.create_user(username="TM202200"+str(i), password="TM202200"+str(i))
            	t.save()
        except:
            pass
class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20220713_1357'),
    ]

    operations = [
        migrations.RunPython(initialize)
    ]
