# Generated by Django 4.0.4 on 2022-08-18 14:29

from django.db import migrations, transaction
from django.contrib.auth.models import User
def initialize(apps, schema_editor):
    for i in range(1000,3000):
        with transaction.atomic():
            t = User.objects.create_user(username="TM20220"+str(i), password="TM20220"+str(i))
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20220815_0450'),
    ]

    operations = [
        migrations.RunPython(initialize)
    ]
